---
title: "Code and Data for NMFS Data Analysis Sections of Pearse et al. (2019) -- Nature Ecology and Evolution"
output: github_document
---



This repository holds the data and code to render the results provided by analyses
done by the Southwest Fisheries Science Center coauthors on Pearse et al. (2019) ---
"Sex-dependent dominance maintains migration supergene in rainbow trout" 


The scripts were written and executed by different authors as follows:

* 100 series.  Steve Lindley,  `steve.lindley@noaa.gov`
* 200 series.  Matthew "Mac" Campbell, `drmaccampbell@gmail.com`
* 300 series.  Eric C. Anderson, `eric.anderson@noaa.gov`

The R scripts rely on a variety of packages that are either from CRAN or Bioconductor, 
unless noted otherwise in the code.

A few large, standard data sources like the WorldClim data set and Natural Earth Data
which were used in analyses are not included here.  Those wishing to reproduce the
results will need to acquire those and modify the scripts to have appropriate path
references to those sources. In particular:

- 203-Extended-Data-Figure-10-etc.R requires dowlnoading publicly available WorldClim data (see code comments for specifics).
- 301-Main-Paper-Figure-2-e.R requires downloading a number of publicly available spatial data sets (see code comments for specifics).



